const myList= {
    "AM101": "Mathematics-I",
    "AP101": "Physics",
    "EE105": "Basic Electrical Engineering-II",
    "ME101": "Computer Aided Engineering Graphics 1",
    "CH103": "Unit Processes in Organic Synthesis",
    "EC101": "Basic Electronics and Communication Engineering",
    "ME105": "Computer Aided Engineering Graphics 2",
    "AC101": "Applied Chemistry",
    "MC103": "Python Programming",
    "EP103": "Engineering Physics Workshop",
    "BT103": "Applied Aquaculture",
    "ME107": "Basic Mechanical Engineering",
    "CE103": "Testing of Civil Engineering Materials",
    "CO101": "Programming Fundamentals",
    "CS103": "Web Designing",
    "CE101": "Basics Of Civil Engineering",
    "EE103": "Electrical Workshop",
    "EC103": "Electronics Workshop 1",
    "EN103": "Waste and Water Waste Analysis",
    "IT103": "Fundamentals of Web Design",
    "ME103": "Workshop Practice",
    "AE103": "Workshop Practice",
    "PE103": "Workshop Practice",
    "SW103": "Computer Workshop 1",
    "AEC": "As Selected",
    "VAC": "As Selected",
    "AC101"	: "CHEMISTRY",
    "FEC"	: "Foundation Elective Course",
    "AE201"	: "ENGINEERING MECHANICS",
    "AE301"	: "MANUFACTURING TECHNOLOGY",
    "AE303"	: "FLUID MECHANICS AND HYDRAULIC MACHINES",
    "AE307"	: "COMBUSTION GENERATED POLLUTION",
    "AE309"	: "OPERATION RESEARCH",
    "AE311"	: "TYRE TECHNOLOGY",
    "AE317"	: "POWER UNITS AND TRANSMISSION",
    "AE321"	: "ADVANCE STRENGTH OF MATERIALS",
    "AE391"	: "MINI PROJECT",
    "AE393"	: "RESEARCH WORK",
    "AE395"	: "Entrepreneurship and Venture Development",
    "AE401"	: "B.TECH PROJECT-I",
    "AE403"	: "TRAINING SEMINAR",
    "AE405"	: "DESIGN OF AUTOMOBILE COMPONENTS",
    "AE407"	: "PRODUCTION AND OPERATIONS MANAGEMENT",
    "AE411"	: "VEHICLE MAINTENANCE & TRIBOLOGY",
    "AE413"	: "VEHICLE TRANSPORT MANAGEMENT",
    "AP101"	: "PHYSICS - I",
    "BBA303"	: "Entrepreneurship Development",
    "BT201"	: "INTRODUCTION TO BIOTECHNOLOGY",
    "BT203"	: "BIOCHEMISTRY",
    "BT205"	: "GENETICS",
    "BT207"	: "FUNDAMENTAL OF COMPUTATIONAL BIOLOGY",
    "BT301"	: "IMMUNOLOGY AND IMMUNO-TECHNOLOGY",
    "BT303"	: "GENETIC ENGINEERING",
    "BT305"	: "Instrumentation in Biotechnology",
    "BT317"	: "Enzymology and Enzyme Technology",
    "BT319"	: "Drug Design and Delivery",
    "BT323"	: "POPULATION GENETICS",
    "BT325"	: "CELL BIOLOGY",
    "BT391"	: "MINI PROJECT",
    "BT395"	: "Entrepreneurship and Venture Development",
    "BT401"	: "B.TECH PROJECT-I",
    "BT403"	: "TRAINING SEMINAR",
    "BT405"	: "FUNDAMENTALS OF COMPUTATIONAL BIOLOGY",
    "BT407"	: "BIOPROCESS TECH & DOWNSTREAM PROCESS",
    "BT413"	: "NANOBIOTECHNOLOGY",
    "BT421"	: "Pharmacogenomics and Personalized Medicine",
    "CE201"	: "CIVIL ENGINEERING BASICS AND APPLICATIONS",
    "CE203"	: "ENGINEERING MECHANICS",
    "CE205"	: "FLUID MECHANICS",
    "CE207"	: "ENGINEERING ANALYSIS AND DESIGN",
    "CE251"	: "BUILDING MATERIAL & CONSTRUCTION",
    "CE301"	: "ANALYSIS OF DETERMINATE STRUCTURES",
    "CE303"	: "DESIGN OF RCC STRUCTURES",
    "CE305"	: "MECHANICS OF MATERIALS",
    "CE307"	: "ADVANCED GEO-TECHNICAL ENGINEERING",
    "CE309"	: "ENVIRONMENTAL ENGINEERING DESIGN",
    "CE313"	: "EARTHQUAKE TECHNOLOGY",
    "CE315"	: "ROCK ENGINEERING",
    "CE317"	: "SOLID WASTE MANAGEMENT & AIR POLLUTION CONTROL",
    "CE319"	: "APPLICATION OF GEO-INFORMATICS REMOTE SENSING AND GIS IN ENGINEERING",
    "CE321"	: "DISASTER PREPAREDNESS AND MITIGATION",
    "CE327"	: "CLIMATE CHANGE AND SUSTAINABLE DEVELOPMENT",
    "CE391"	: "MINI PROJECT",
    "CE393"	: "RESEARCH WORK",
    "CE395"	: "Entrepreneurship and Venture Development",
    "CE401"	: "B.TECH. PROJECT - I",
    "CE403"	: "TRAINING SEMINAR",
    "CE407"	: "WATER RESOURCES ENGINEERING",
    "CE413"	: "WATER RESOURCES MANAGEMENT",
    "CE415"	: "TRANSPORTATION SAFETY AND ENVIRONMENT",
    "CE423"	: "ADVANCED TRANSPORTATION ENGINEERING",
    "CE427"	: "Wind Loads on Structures",
    "CE429"	: "Disaster Induced Risk",
    "CE431"	: "Cyclonic Hazard Assessment and Mitigation",
    "CE435"	: "Landslide Hazard Assessment and Mitigation",
    "CH201"	: "Chemical Engineering Process Calculations",
    "CH205"	: "Chemical Engineering Thermodynamics",
    "CH207"	: "Engineering Design and Analysis (Process Equipment Design)",
    "CH301"	: "Polymeric Materials",
    "CH303"	: "Mass Transfer -1",
    "CH307"	: "Petroleum Refining Engineering",
    "CH315"	: "Plastic Technology",
    "CH321"	: "Numerical Methods in Chemical Engineering",
    "CH323"	: "Biomaterials",
    "CH391"	: "Mini Project",
    "CH395"	: "Entrepreneurship and Venture Development",
    "CH401"	: "B.TECH. PROJECT I",
    "CH403"	: "TRAINING SEMINAR",
    "CH405"	: "Fiber Technology",
    "CH407"	: "Polymer Blends and Composites",
    "CH417"	: "Polymer Waste Management",
    "CH429"	: "Energy Resources",
    "CO101"	: "PROGRAMMING FUNDAMENTALS",
    "CO201"	: "DATA STRUCTURES",
    "CO203"	: "OBJECT ORIENTED PROGRAMMING",
    "CO205"	: "DISCRETE STRUCTURES",
    "CO207"	: "ENGINEERING ANALYSIS AND DESIGN (MODELING AND SIMULATION)",
    "CO301"	: "SOFTWARE ENGINEERING",
    "CO303"	: "THEORY OF COMPUTATION",
    "CO305"	: "INFORMATION THEORY AND CODING",
    "CO313"	: "COMPUTER GRAPHICS",
    "CO325"	: "Probability And Statistics",
    "CO327"	: "MACHINE LEARNING",
    "CO391"	: "MINI PROJECT",
    "CO393"	: "RESEARCH WORK",
    "CO395"	: "Entrepreneurship and Venture Development",
    "CO401"	: "B.TECH PROJECT-I",
    "CO403"	: "TRAINING SEMINAR",
    "CO411"	: "Computer Vision",
    "CO415"	: "WIRELESS AND MOBILE COMPUTING",
    "CO423"	: "SWARM & EVOLUTIONARY COMPUTING",
    "CO425"	: "Information and Network Security",
    "CO427"	: "Web Technology",
    "CO429"	: "Neural Networks",
    "CO431"	: "Reinforcement Learning",
    "CO433"	: "Distributed Systems",
    "CS251"	: "DATA STRUCTURE",
    "EC201"	: "ANALOG ELECTRONICS – I",
    "EC203"	: "DIGITAL DESIGN - I",
    "EC205"	: "SIGNALS & SYSTEMS",
    "EC207"	: "ENGINEERING ANALYSIS & DESIGN (NETWORK ANALYSIS AND SYNTHESIS)",
    "EC251"	: "BASIC ELECTRONICS & INSTRUMENTATION",
    "EC261"	: "ANALOG  ELECTRONICS",
    "EC271a"	: "DIGITAL ELECTRONICS",
    "EC301"	: "DIGITAL COMMUNICATION",
    "EC303"	: "LINEAR INTEGRATED CIRCUITS",
    "EC305"	: "Semiconductor Device Electronics",
    "EC307"	: "ANTENNA DESIGN",
    "EC309"	: "Bio-Medical Electronics & Instrumentation",
    "EC311"	: "ALGORITHMS ANALYSIS AND DESIGN",
    "EC313"	: "MICROPROCESSORS AND INTERFACING",
    "EC315"	: "COMPUTER COMMUNICATION NETWORKS",
    "EC323"	: "CONTROL SYSTEMS",
    "EC325"	: "Probability and Random Process",
    "EC391"	: "MINI PROJECT",
    "EC393"	: "RESEARCH WORK",
    "EC395"	: "Entrepreneurship and Venture Development",
    "EC401"	: "B.TECH PROJECT-I",
    "EC403"	: "TRAINING SEMINAR",
    "EC407"	: "OPTICAL COMMUNICATION",
    "EC409"	: "COMPUTER VISION",
    "EC431"	: "MEMS and Sensor Design",
    "EC455"	: "Data Analytics",
    "EC457"	: "Natural Language Processing",
    "EE101"	: "BASIC ELECTRICAL ENGINEERING",
    "EE201"	: "NETWORK ANALYSIS & SYNTHESIS",
    "EE203"	: "ELECTRONIC DEVICES AND CIRCUITS",
    "EE205"	: "ELECTROMECHANICAL ENERGY CONVERSION AND TRANSFORMER",
    "EE207a"	: "Electromagnetic Field Theory",
    "EE251"	: "ELECTRONIC INSTRUMENTATION AND MEASUREMENTS",
    "EE301"	: "POWER ELECTRONICS",
    "EE303"	: "POWER TRANSMISSION AND DISTRIBUTION",
    "EE305"	: "SIGNALS AND SYSTEMS",
    "EE307"	: "POWER STATION PRACTICES",
    "EE309"	: "SPECIAL ELECTRICAL MACHINES",
    "EE313a"	: "Engineering Analysis and Design",
    "EE315"	: "DIGITAL CONTROL AND STATE VARIABLE ANALYSIS",
    "EE317"	: "RENEWABLE ENERGY SYSTEMS",
    "EE319"	: "DIGITAL SYSTEM DESIGN",
    "EE321"	: "SOFT COMPUTING TECHNIQUES",
    "EE323"	: "FUNDAMENTALS OF MACHINE LEARNING",
    "EE325"	: "INTERNET OF THINGS",
    "EE357"	: "UTILIZATION OF ELECTRICAL ENERGY",
    "EE393"	: "RESEARCH WORK",
    "EE395"	: "Entrepreneurship and Venture Development",
    "EE401"	: "B.TECH PROJECT-I",
    "EE403"	: "TRAINING SEMINAR",
    "EE407"	: "INSTRUMENTATION AND MEASUREMENT",
    "EE409"	: "SWITCHGEAR AND PROTECTION",
    "EE419"	: "PULSE WIDTH MODULATION FOR POWER CONVERTERS",
    "EN201"	: "STRENGTH OF MATERIALS",
    "EN203"	: "ENGINEERING & ENVIRONMENTAL SURVEYING",
    "EN205"	: "ENVIRONMENTAL CHEMISTRY & MICROBIOLOGY",
    "EN207"	: "ENGINEERING ANALYSIS & DESIGN",
    "EN301"	: "WASTE WATER ENGINEERING: DESIGN AND APPLICATIONS",
    "EN303"	: "INSTRUMENTATION TECHNIQUES FOR ENVIRONMENTAL MONITORING",
    "EN305"	: "SOIL POLLUTION AND REMEDIATION",
    "EN307"	: "PLANNING AND DESIGN OF ENVIRONMENTAL ENGINEERING WORKS",
    "EN309"	: "Water Resources System",
    "EN311"	: "CLIMATE CHANGE & CDM",
    "EN317"	: "Environmental Management",
    "EN391"	: "MINI PROJECT",
    "EN393"	: "RESEARCH WORK",
    "EN395"	: "Entrepreneurship and Venture Development",
    "EN401"	: "B.TECH PROJECT-I",
    "EN403"	: "TRAINING SEMINAR",
    "EN409"	: "INDUSTRIAL WASTE MANAGEMENT",
    "EN411"	: "OCCUPATIONAL HAZARDS, HEALTH & SAFETY",
    "EN421"	: "Design of Water Distribution Network",
    "EP201"	: "INTRODUCTION TO COMPUTING",
    "EP203"	: "MATHEMATICAL PHYSICS",
    "EP205"	: "CLASSICAL AND QUANTUM MECHANICS",
    "EP207"	: "DIGITAL ELECTRONICS (ENGINEERING ANALYSIS AND DESIGN)",
    "EP301"	: "SEMICONDUCTOR DEVICES",
    "EP303"	: "ELECTROMAGNETIC THEORY, ANTENNAS AND PROPAGATION",
    "EP305"	: "ATOMIC AND MOLECULAR PHYSICS",
    "EP307"	: "BIOPHYSICS",
    "EP309"	: "QUANTUM INFORMATION AND COMPUTING",
    "EP317"	: "Advanced Semiconductor Device Physics",
    "EP321"	: "Advanced Wafer Processing",
    "EP401"	: "B.TECH PROJECT-I",
    "EP403"	: "TRAINING SEMINAR",
    "EP405"	: "VLSI AND FPGA DESIGN",
    "EP411"	: "ADVANCED SIMULATION TECHNIQUES IN PHYSICS",
    "EP415"	: "NANO SCIENCE AND TECHNOLOGY",
    "EP419"	: "INTRODUCTION TO AUTOMATION AND MOTION CONTROL",
    "EP423"	: "SPACE AND ATMOSPHERIC SCIENCE-I",
    "EP427a"	: "Advanced Materials for Photonic Devices",
    "FEC10"	: "COMMUNICATION  SKILLS",
    "FEC11"	: "Soft Skills and Personality Development ",
    "FEC12"	: "BUSINESS  COMMUNICATION AND PRESENTATION SKILLS",
    "FEC14"	: "APPRECIATION OF SHORT STORIES",
    "FEC15"	: "APPRECIATION OF POETRY & POSE",
    "FEC18"	: "FINANCIAL  STATEMENTS ANALYSIS",
    "FEC2"	: "SPORTS II",
    "FEC22"	: "YOGA",
    "FEC24"	: "MUSIC",
    "FEC27"	: "PROFESSIONAL ETHICS & HUMAN VALUES",
    "FEC3"	: "PHYSICAL EDUCATION AND SPORTS",
    "FEC37"	: "FRENCH",
    "FEC40"	: "GERMAN",
    "FEC45"	: "ENGINEERING  EXPLORATION",
    "FEC46"	: "TECHNICAL  COMMUNICATION",
    "FEC48"	: "INTRODUCTION TO BIOLOGICAL SCIENCE",
    "FEC49"	: "SKETCHING & RENDERING",
    "FEC51"	: "Entrepreneurship Exploration",
    "FEC52"	: "Extension and Outreach Activities",
    "FEC54"	: "Negotiation and Leadership",
    "FEC56"	: "UNIVERSAL HUMAN VALUES : UNDERSTANDING HARMONY",
    "FEC58"	: "Science and Practice of Happiness",
    "FEC7"	: "INTRODUCTION  TO ENVIRONMENTAL SCIENCE",
    "HU301a"	: "Engineering Economics",
    "HU305"	: "Macroeconomics",
    "HU307"	: "Basic Econometrics",
    "HU309"	: "Indian Economy",
    "HU313"	: "Creative Writing Skills",
    "HU315"	: "Non-Verbal Communication",
    "HU353a"	: "International Trade",
    "HU403"	: "Economic Growth",
    "HU409"	: "Soft Skills Development",
    "HU413"	: "Advanced Spoken Skills",
    "IT201"	: "DATA STRUCTURES",
    "IT203"	: "OBJECT ORIENTED PROGRAMMING",
    "IT205"	: "DISCRETE  STRUCTURES",
    "IT207"	: "ENGINEERING ANALYSIS AND DESIGN(MODELING & SIMULATION)",
    "IT301"	: "THEORY OF COMPUTATION",
    "IT303"	: "COMPUTER NETWORKS",
    "IT307"	: "PATTERN RECOGNITION",
    "IT315"	: "Distributed Systems",
    "IT317"	: "SOFT COMPUTING",
    "IT319"	: "Data Compression",
    "IT321"	: "MALWARE ANALYSIS",
    "IT323"	: "MACHINE LEARNING",
    "IT325"	: "SECURE CODING",
    "IT359"	: "JAVA PROGRAMMING",
    "IT391"	: "MINI PROJECT",
    "IT393"	: "RESEARCH WORK",
    "IT395"	: "Entrepreneurship and Venture Development",
    "IT401"	: "B.TECH PROJECT-I",
    "IT403"	: "TRAINING SEMINAR",
    "IT405"	: "DATA-WAREHOUSE AND DATA MINING",
    "IT407"	: "INFORMATION AND NETWORK SECURITY",
    "IT411"	: "DIGITAL IMAGE PROCESSING",
    "IT425"	: "NATURAL LANGUAGE PROCESSING",
    "IT429"	: "CYBER LAWS",
    "IT431"	: "INFORMATION SECURITY AND AUDIT",
    "IT433"	: "MULTI MODAL DATA PROCESSING",
    "MA101"	: "MATHEMATICS - I",
    "MA261"	: "NUMERICAL AND ENGINEERING OPTIMIZATION METHODS",
    "MBA-107" : "MARKETING MANAGEMENT",
    "MBAMK211" : "Digital Marketing Strategy",
    "MBAMK213" : "Consumer Behaviour",
    "MBAMK215" : "Product and Brand Management",
    "MBAMK219" : "Marketing Research",
    "MBASC211" : "Operational Analytics",
    "MBASC221" : "Supply Chain Planning and Execution",
    "MBEALS2"	: "ACTION LEARNING SEGMENT 2",
    "MC201"	: "DISCRETE MATHEMATICS",
    "MC203"	: "MATHEMATICS-III",
    "MC205"	: "PROBABILITY & STATISTICS",
    "MC207"	: "ENGINEERING ANALYSIS AND DESIGN (DIFFERENTIAL EQUATIONS AND APPLICATIONS)",
    "MC251"	: "APPLIED MATHEMATICS",
    "MC301"	: "OPERATING SYSTEM",
    "MC303"	: "STOCHASTIC PROCESSES",
    "MC305"	: "OPERATIONS RESEARCH",
    "MC307"	: "OBJECT ORIENTED PROGRAMMING",
    "MC315"	: "MODERN ALGEBRA",
    "MC317"	: "Numerical Methods for Ordinary Diffrential Equations",
    "MC391"	: "MINI PROJECT",
    "MC393"	: "RESEARCH WORK",
    "MC395"	: "Entrepreneurship and Venture Development",
    "MC401"	: "B.TECH PROJECT-I",
    "MC403"	: "TRAINING SEMINAR",
    "MC405"	: "GRAPH THEORY",
    "MC407"	: "CRYPTOGRAPHY & NETWORK SECURITY",
    "MC409"	: "MATHEMATICAL MODELING & SIMULATION",
    "MC419"	: "Machine Learning",
    "ME101"	: "BASIC MECHANICAL ENGINEERING",
    "ME103"	: "WORKSHOP PRACTICE",
    "ME201"	: "MECHANICS OF SOLIDS",
    "ME203"	: "THERMAL ENGINEERING - I",
    "ME205"	: "MACHINE DRAWING AND SOLID MODELING",
    "ME207"	: "ENGINEERING ANALYSIS AND DESIGN",
    "ME251"	: "ENGINEERING MECHANICS",
    "ME261"	: "KINEMATIC AND DYNAMIC OF MACHINES",
    "ME301"	: "FLUID SYSTEMS",
    "ME303"	: "DYNAMICS OF MACHINES",
    "ME351a"	: "POWER PLANT ENGINEERING",
    "ME353"	: "RENEWABLE SOURCES OF ENERGY",
    "ME361"	: "INDUSTRIAL ENGINEERING",
    "ME365"	: "COMPUTATIONAL FLUID DYNAMICS",
    "ME367"	: "FINITE ELEMENT METHODS",
    "ME371"	: "VALUE ENGINEERING",
    "ME391"	: "Mini Project",
    "ME393"	: "Research Work",
    "ME395"	: "Entrepreneurship and Venture Development",
    "ME401"	: "B.TECH PROJECT-I",
    "ME403"	: "TRAINING SEMINAR",
    "ME407"	: "REFRIGERATION & AIR CONDITIONING",
    "ME409"	: "MECHATRONICS & CONTROL",
    "ME411"	: "I.C. ENGINES",
    "ME413"	: "METROLOGY",
    "ME419"	: "ROBOTICS & AUTOMATION",
    "ME423"	: "ADVANCED MANUFACTURING PROCESSES",
    "ME427"	: "OPERATIONS RESEARCH",
    "ME429"	: "INDUSTRIAL TRIBOLOGY",
    "ME431"	: "NON-CONVENTIONAL ENERGY SOURCES",
    "ME435"	: "OPTIMIZATION TECHNIQUES",
    "MG301"	: "Fundamentals of Management",
    "MOOC301"	: "MOOC COURSE 301",
    "MOOC303"	: "MOOC COURSE 303",
    "MOOC401"	: "MOOC401",
    "MOOC403"	: "MOOC403",
    "MS399"	: "Community Engagement(Mentoring School Students)",
    "PE201"	: "ENGINEERING MATERIALS & METALLURGY",
    "PE203"	: "THERMAL ENGINEERING-I",
    "PE205"	: "MANUFACTURING MACHINES",
    "PE207"	: "ENGINEERING ANALYSIS AND DESIGN(MODELING  AND SIMULATION)",
    "PE251"	: "ENGINEERING MATERIALS AND METALLURGY",
    "PE261"	: "QUANTITATIVE TECHNIQUES",
    "PE301"	: "CASTING TECHNOLOGY",
    "PE303"	: "PRODUCTION PLANNING & CONTROL",
    "PE305"	: "ADVANCE MACHINE DESIGN",
    "PE315"	: "MECHATRONICS",
    "PE351"	: "Advance Machining Process",
    "PE353"	: "SUPPLY CHAIN MANAGEMENT",
    "PE353a"	: "SUPPLY CHAIN MANAGEMENT",
    "PE357"	: "PRODUCT DESIGN & SIMULATION",
    "PE361"	: "TOTAL QUALITY MANAGEMENT",
    "PE361a"	: "TOTAL QUALITY MANAGEMENT",
    "PE395"	: "Entrepreneurship and Venture Development",
    "PE401"	: "B.TECH PROJECT-I",
    "PE403"	: "TRAINING SEMINAR",
    "PE405"	: "METAL FORMING & PRESS WORKING",
    "PE407"	: "QUANTITATIVE TECHNIQUES",
    "PE411"	: "COMPUTER INTEGRATED DESIGN AND MANUFACTURING",
    "PE417"	: "MATERIALS MANAGEMENT",
    "PE419"	: "PROJECT MANAGEMENT",
    "PE421"	: "RELIABILITY, MAINTENANCE & SAFETY ENGINEERING",
    "PE423"	: "THERMAL SPRAY TECHNOLOGY",
    "SE201"	: "DATA STRUCTURES",
    "SE203"	: "OBJECT ORIENTED PROGRAMMING",
    "SE205a": "Operating System",
    "SE207a"	: "Engineering Analysis and Design ( Software Engineering)",
    "SE301"	: "OBJECT ORIENTED SOFTWARE ENGINEERING",
    "SE301a"	: "Software Testing",
    "SE303a"	: "Software Quality Metrics",
    "SE305"	: "Software Requirement Engineering",
    "SE313"	: "Advanced Data Structures",
    "SE323"	: "THEORY OF COMPUTATION",
    "SE325"	: "WEB TECHNOLOGY",
    "SE327"	: "METHODS FOR DATA ANALYSIS",
    "SE333"	: "Minor Project",
    "SE391"	: "MINI PROJECT",
    "SE393"	: "RESEARCH WORK",
    "SE395"	: "Entrepreneurship and Venture Development",
    "SE401"	: "B.TECH PROJECT-I",
    "SE403"	: "TRAINING SEMINAR",
    "SE405"	: "SOFTWARE PROJECT MANAGEMENT",
    "SE407a"	: "Data Warehousing and Data Mining",
    "SE409"	: "SOFTWARE MAINTENANCE",
    "SE425"	: "Intellectual Property Rights & Cyber laws",
    "SE427"	: "Software Project Management",
    "SE429"	: "Data Warehouse & Data Mining"
}
