const myList = {
    "AC101": "CHEMISTRY",
    "AC101": "APPLIED CHEMISTRY",
    "ACPT-901": "Spectroscopy: Application for Structure Determination",
    "ACPT-902": "Analytical Techniques for Material Characterization",
    "AE103": "WORKSHOP PRACTICE",
    "AE201": "ENGINEERING MECHANICS",
    "AE203": "THERMODYNAMICS",
    "AE205": "MANUFACTURING MACHINES",
    "AE207": "ENGINEERING ANALYSIS AND DESIGN",
    "AE301": "MANUFACTURING TECHNOLOGY",
    "AE303": "FLUID MECHANICS AND HYDRAULIC MACHINES",
    "AE307": "COMBUSTION GENERATED POLLUTION",
    "AE309": "OPERATION RESEARCH",
    "AE311": "TYRE TECHNOLOGY",
    "AE317": "POWER UNITS AND TRANSMISSION",
    "AE321": "ADVANCE STRENGTH OF MATERIALS",
    "AE391": "MINI PROJECT",
    "AE393": "RESEARCH WORK",
    "AE395": "Entrepreneurship and Venture Development",
    "AE401": "B.TECH PROJECT-I",
    "AE403": "TRAINING SEMINAR",
    "AE407": "PRODUCTION AND OPERATIONS MANAGEMENT",
    "AE411": "VEHICLE MAINTENANCE & TRIBOLOGY",
    "AE413": "VEHICLE TRANSPORT MANAGEMENT",
    "AEC1": "Appreciation of Fiction",
    "AEC10": "German",
    "AEC11": "Soft Skills and Personality Development",
    "AEC12": "Japanese",
    "AEC13": "Logical Reasoning",
    "AEC15": "Public Speaking",
    "AEC18": "Spoken Skills in English",
    "AEC19": "Technical Communication",
    "AEC2": "Appreciation of Poetry & Prose",
    "AEC3": "Appreciation of Short Stories",
    "AEC4": "Business Communication and Presentation Skills",
    "AEC5": "Communication Skills",
    "AEC6": "Communicative Hindi (Only for foreign national students)",
    "AI501": "ADVANCE DATA STRUCTRE AND ALGORITHM",
    "AI503": "PRINCIPLES OF AI",
    "AI5201": "Seminar",
    "AI5305": "Information and Network Security",
    "AI5403": "Advance Database Management System",
    "AI601": "MAJOR PROJECT I",
    "AI6209": "Predictive Modelling",
    "AI6307": "Block Chain and Applications",
    "AI6405": "Advance Computer Vision",
    "AI651": "RESEARCH PROJECT",
    "AM101": "MATHEMATICS-I",
    "AM-501C": "INTRODUCTION TO MATHEMATICAL SOFTWARE",
    "AM-502A": "APPROXIMATION THEORY",
    "AM-503A": "GEOMETRIC FUNCTION THEORY",
    "AM-503C": "TENSOR ANALYSIS AND RELATIVISTIC MECHANICS",
    "AM-503D": "QUANTUM CALCULUS",
    "AM-504C": "Numerical Methods and Partial Differential Equations",
    "AM-505C": "GROUP RINGS",
    "AM-505D": "QUANTUM INFORMATION THEORY",
    "AP101": "PHYSICS - I",
    "AP101": "PHYSICS",
    "BA201a": "Intermediate Microeconomics – II",
    "BA202a": "INTERMEDIATE MACROECONOMICS-II",
    "BA203a": "Mathematical Methods for Economics – II",
    "BA204a": "STATISTICAL METHODS FOR ECONOMICS",
    "BA301a": "Development Economics I",
    "BA302a": "Indian Economy - I",
    "BA303a": "Predictive Modeling",
    "BAD301": "Economics of Health and  Education",
    "BAD302": "Applied Econometrics",
    "BAD303": "Economics History of India (1857-1947)",
    "BAD304": "Money and Financial Markets",
    "BAD305": "Public Economics",
    "BAG201": "Financial  Management",
    "BAG202": "E-Commerce",
    "BBA201": "ORGANIZATION BEHAVIOR",
    "BBA202": "MARKETING MANAGEMENT",
    "BBA203": "BUSINESS ETHICS AND CORPORATE SOCIAL RESPONSIBILITY",
    "BBA204": "MANAGEMENT ACCOUNTING",
    "BBA205": "ENVIRONMENTAL SCIENCE (NUES)",
    "BBA301": "INCOME-TAX LAW AND PRACTICE",
    "BBA302": "FINANCIAL MANAGEMENT",
    "BBA303": "Entrepreneurship Development",
    "BBA304": "SUMMER TRAINING REPORT & VIVA VOICE",
    "BBAF02a": "Investment banking and financial services",
    "BBAF04a": "Investment Analysis & p; Portfolio Management",
    "BBAH02a": "Organisational development",
    "BBAH03a": "Strategic HRM",
    "BBAM01a": "Consumer Behaviourï¿",
    "BBAM03a": "Integrated marketing communication",
    "BIO501": "INTRODUCTION TO BIOINFORMATICS",
    "BIO503": "ADVANCED PROTEOMICS",
    "BIO5201": "OPEN AREA SEMINAR-I",
    "BIO5301": "DATA WAREHOUSING AND DATA MINING",
    "BIO5407": "OMICS IN MEDICINE",
    "BIO601": "MAJOR PROJECT I",
    "BIO6207": "Entrepreneurship",
    "BIO6301": "Nanotechnology in Healthcare",
    "BIO6401": "Drug Design and Discovery",
    "BIO651": "RESEARCH PROJECT",
    "BT103": "APPLIED AQUACULTURE",
    "BT201": "INTRODUCTION TO BIOTECHNOLOGY",
    "BT203": "BIOCHEMISTRY",
    "BT205": "GENETICS",
    "BT207": "FUNDAMENTAL OF COMPUTATIONAL BIOLOGY",
    "BT301": "IMMUNOLOGY AND IMMUNO-TECHNOLOGY",
    "BT303": "GENETIC ENGINEERING",
    "BT305": "Instrumentation in Biotechnology",
    "BT317": "Enzymology and Enzyme Technology",
    "BT319": "Drug Design and Delivery",
    "BT323": "POPULATION GENETICS",
    "BT325": "CELL BIOLOGY",
    "BT391": "MINI PROJECT",
    "BT393": "RESEARCH WORK",
    "BT395": "Entrepreneurship and Venture Development",
    "BT401": "B.TECH PROJECT-I",
    "BT403": "TRAINING SEMINAR",
    "BT405": "FUNDAMENTALS OF COMPUTATIONAL BIOLOGY",
    "BT407": "BIOPROCESS TECH & DOWNSTREAM PROCESS",
    "BT413": "NANOBIOTECHNOLOGY",
    "BT421": "Pharmacogenomics and Personalized Medicine",
    "BT425": "BIOMATERIALS",
    "C&I501": "SYSTEM THEORY",
    "C&I503": "MEASUREMENT & INSTRUMENTATION",
    "C&I5201": "SEMINAR",
    "C&I5303": "NONLINEAR CONTROL THEORY",
    "C&I5401": "ANALOG & DIGITAL ELECTRONICS",
    "C&I601": "MAJOR PROJECT I",
    "C&I6205a": "Artificial Intelligence",
    "C&I6209a": "Artificial Intelligence",
    "C&I651": "RESEARCH PROJECT",
    "CAD501": "SYSTEM MODELLING, SIMULATION AND ANALYSIS",
    "CAD503": "COMPUTATIONAL MECHANICS OF MATERIALS",
    "CAD5201": "SMART MATERIALS",
    "CAD5303": "MUMERICAL METHODS IN ENGINEERING",
    "CAD5401": "ADVANCED VIBRATION AND CONTROL",
    "CCE-201": "MECHANICS OF SOLIDS",
    "CCE-203": "ENGINEERING SURVEY",
    "CCE-205": "SOIL MECHANICS",
    "CCE-301": "ANALYSIS OF INDETERMINATE STRUCTURES",
    "CCE-303": "GEOTECHNICAL ENGINEERING",
    "CCE-309": "ENVIRONMENTAL ENGINEERING DESIGN",
    "CCE-351": "GEOINFORMATICS AND ITS APPLICATION",
    "CCE-401": "DESIGN OF STEEL STRUCTURES",
    "CCE-403": "WATER RESOURCES ENGINEERING",
    "CCE-405": "B.TECH. PROJECT",
    "CCE-411": "TRANSPORTATION SAFETY AND ENVIRONMENT",
    "CCE-419": "ADVANCED TRANSPORTATION ENGINEERING",
    "CE101": "BASIC CIVIL ENGINEERING",
    "CE103": "TESTING OF CIVIL ENGINEERING MATERIALS",
    "CE201": "CIVIL ENGINEERING BASICS AND APPLICATIONS",
    "CE203": "ENGINEERING MECHANICS",
    "CE205": "FLUID MECHANICS",
    "CE207": "ENGINEERING ANALYSIS AND DESIGN",
    "CE251": "BUILDING MATERIAL & CONSTRUCTION",
    "CE301": "ANALYSIS OF DETERMINATE STRUCTURES",
    "CE303": "DESIGN OF RCC STRUCTURES",
    "CE305": "MECHANICS OF MATERIALS",
    "CE307": "ADVANCED GEO-TECHNICAL ENGINEERING",
    "CE309": "ENVIRONMENTAL ENGINEERING DESIGN",
    "CE313": "EARTHQUAKE TECHNOLOGY",
    "CE315": "ROCK ENGINEERING",
    "CE317": "SOLID WASTE MANAGEMENT & AIR POLLUTION CONTROL",
    "CE319": "APPLICATION OF GEO-INFORMATICS REMOTE SENSING AND GIS IN ENGINEERING",
    "CE321": "DISASTER PREPAREDNESS AND MITIGATION",
    "CE325": "HUMAN VALUES & ETHICS IN DISASTER MANAGEMENT",
    "CE327": "CLIMATE CHANGE AND SUSTAINABLE DEVELOPMENT",
    "CE393": "RESEARCH WORK",
    "CE395": "Entrepreneurship and Venture Development",
    "CE401": "B.TECH. PROJECT - I",
    "CE403": "TRAINING SEMINAR",
    "CE407": "WATER RESOURCES ENGINEERING",
    "CE413": "WATER RESOURCES MANAGEMENT",
    "CE415": "TRANSPORTATION SAFETY AND ENVIRONMENT",
    "CE423": "ADVANCED TRANSPORTATION ENGINEERING",
    "CE427": "Wind Loads on Structures",
    "CE429": "Disaster Induced Risk",
    "CE431": "Cyclonic Hazard Assessment and Mitigation",
    "CE435": "Landslide Hazard Assessment and Mitigation",
    "CEC-301": "DIGITAL SIGNAL PROCESSING",
    "CEC-305": "Semiconductor Device Electronics",
    "CEC-307": "Antenna Design",
    "CEC-323": "Control Systems",
    "CEC-401": "INFORMATION THEORY & CODING",
    "CEC-403": "WIRELESS COMMUNICATION",
    "CEC-405": "B.TECH. PROJECT",
    "CEC-409": "COMPUTER VISION",
    "CEC-427": "OPTICAL COMMUNICATION",
    "CEE-201": "DIGITAL CIRCUITS AND SYSTEM",
    "CEE-203": "CONTROL SYSTEMS",
    "CEE-205": "ASYNCHRONOUS AND SYNCHRONOUS MACHINES",
    "CEE-301": "POWER ELECTRONICS",
    "CEE-303": "POWER SYSTEMS AND ANALYSIS",
    "CEE-309": "SPECIAL ELECTRICAL MACHINES",
    "CEE-313": "LINEAR INTEGRATED CIRCUITS",
    "CEE-355": "INSTRUMENTATION SYSTEMS",
    "CEE-401": "UTILIZATION OF ELECTRICAL ENERGY",
    "CEE-403": "ELECTRIC DRIVES",
    "CEE-405": "B.TECH. PROJECT",
    "CEE-411": "POWER SYSTEM RELIABILITY",
    "CEE-421": "HVDC",
    "CH103": "UNIT PROCESS IN CHEMICAL SYNTHESIS-1",
    "CH201": "Chemical Engineering Process Calculations",
    "CH203": "Transport Phenomena",
    "CH205": "Chemical Engineering Thermodynamics",
    "CH207": "Engineering Design and Analysis (Process Equipment Design)",
    "CH301": "Polymeric Materials",
    "CH303": "Mass Transfer -1",
    "CH307": "Petroleum Refining Engineering",
    "CH315": "Plastic Technology",
    "CH321": "Numerical Methods in Chemical Engineering",
    "CH323": "Biomaterials",
    "CH395": "Entrepreneurship and Venture Development",
    "CH401": "B.TECH. PROJECT I",
    "CH403": "TRAINING SEMINAR",
    "CH405": "Fiber Technology",
    "CH407": "Polymer Blends and Composites",
    "CH417": "Polymer Waste Management",
    "CH429": "Energy Resources",
    "CHU-201": "PROFESSIONAL ETHICS AND HUMAN VALUES",
    "CME-301": "HEAT TRANSFER",
    "CME-303": "REFRIGERATION AND AIR CONDITIONING",
    "CME-305": "OPERATIONS RESEARCH",
    "CME-307": "ADVANCED MACHINING PROCESS",
    "CME-361": "INDUSTRIAL ENGINEERING",
    "CME-401": "FLEXIBLE MANUFACTURING SYSTEMS",
    "CME-403": "MACHINE DESIGN",
    "CME-405": "B.TECH. PROJECT",
    "CME-407": "MECHATRONICS",
    "CME-411": "COMBUSTION GENERATED POLLUTION",
    "CO101": "PROGRAMMING FUNDAMENTALS",
    "CO201": "DATA STRUCTURES",
    "CO203": "OBJECT ORIENTED PROGRAMMING",
    "CO205": "DISCRETE STRUCTURES",
    "CO207": "ENGINEERING ANALYSIS AND DESIGN (MODELING AND SIMULATION)",
    "CO301": "SOFTWARE ENGINEERING",
    "CO303": "THEORY OF COMPUTATION",
    "CO305": "INFORMATION THEORY AND CODING",
    "CO313": "COMPUTER GRAPHICS",
    "CO325": "Probability And Statistics",
    "CO327": "MACHINE LEARNING",
    "CO391": "MINI PROJECT",
    "CO393": "RESEARCH WORK",
    "CO395": "Entrepreneurship and Venture Development",
    "CO401": "B.TECH PROJECT-I",
    "CO403": "TRAINING SEMINAR",
    "CO411": "Computer Vision",
    "CO415": "WIRELESS AND MOBILE COMPUTING",
    "CO423": "SWARM & EVOLUTIONARY COMPUTING",
    "CO425": "Information and Network Security",
    "CO427": "Web Technology",
    "CO429": "Neural Networks",
    "CO431": "Reinforcement Learning",
    "CO433": "Distributed Systems",
    "CS103": "WEB DESIGNING",
    "CS251": "DATA STRUCTURE",
    "CSE501": "ADVANCED DATABASE MANAGEMENT SYSTEMS",
    "CSE503": "ADVANCED ALGORITHMS AND DATA STRUCTURES",
    "CSE5201": "SEMINAR",
    "CSE5307": "PARALLEL COMPUTER ARCHITECTURE",
    "CSE5401": "ARTIFICIAL INTELLIGENCE AND EXPERT SYSTEMS",
    "CSE601": "MAJOR PROJECT I",
    "CSE6205": "Advances in Internet & Web Technology",
    "CSE6301": "Natural Language Processing",
    "CSE6401": "Pattern Recognition",
    "DD101": "WORLD OF DESIGN",
    "DD103": "SKETCHING 2D/3D & RENDERING",
    "DD105": "ELEMENTS OF DESIGNS",
    "DD107": "TINKERING STUDIO",
    "DD109": "COMPUTER GRAPHICS 2D",
    "DD111": "FIELD STUDY/DESIGN PROJECT-1",
    "DD201": "PHYSICAL ERGONOMICS",
    "DD203": "DESIGN AND PEOPLE",
    "DD205": "BASICS OF INTERACTION DESIGN",
    "DD207": "BASICS OF PHOTOGRAPHY AND VIDEOGRAPHY",
    "DD209": "VISUAL DESIGN",
    "DD211": "DESIGN PROJECT-3",
    "DD301": "UNIVERSAL DESIGN",
    "DD303": "DESIGN THINKING",
    "DD311": "DESIGN PROJECT-5",
    "DD313": "INTERNSHIP-1",
    "DD321": "Research Techniques in Cognition, Perception and Creativity",
    "DD331": "Typography- 2",
    "DD341": "Animation- 2",
    "DD351": "Exploring the Taxonomy of Product Design",
    "DD371": "Experimental Film Making",
    "DD401": "Design Research",
    "DD411": "Internship - 3",
    "DD421": "Model Making and Prototyping",
    "DD423": "Mobility Design",
    "DD425": "Applied Ergonomics",
    "DD427": "Medical Equipment Design",
    "DD431": "Graphic Design",
    "DD433": "New Media Studies",
    "DD435": "Advance Animation and Moving Images Design",
    "DD437": "Branding- 2",
    "DD441": "Augmented and Virtual Reality",
    "DD443": "Advanced Material Processes and Finishes",
    "DD445": "Design for UX",
    "DD447": "Service Design",
    "DD461": "Visual Merchandising and Retail Merchandising",
    "DD467": "Fashion Management and Entrepreneurship",
    "DD471": "Motion Graphics and Animation Fundamentals",
    "DD473": "Current Trends and Social Media",
    "DD475": "Film Project",
    "DD477": "Production Management",
    "DD501": "Design Project 1",
    "DD511": "Digital Representation Techniques",
    "DD513": "Narrative Building",
    "DD515": "User Centred Design",
    "DD517": "Behavioural Dynamics in Design",
    "DD521": "Representation Techniques",
    "DD523": "INDUSTRIAL DESIGN PROCESS AND PRACTICE",
    "DD525": "Material and Process for Design",
    "DD527": "Behavioral Dynamics in Design",
    "DD531": "Visual Culture & Media Practices",
    "DD533": "Communication Design Fundamentals",
    "DD535": "Image Fabrication & Visualization",
    "DD537": "Video, Sound & Cinematography",
    "DD551": "Sketching and Rendering Skills",
    "DD553": "Model Making",
    "DD555": "Computer Aided 3D Modelling",
    "DD557": "Physical and Cognitive Dynamics in Vehicle Design",
    "DD601": "ORGANIZATIONAL MODEL FOR ENTREPRENEURSHIP",
    "DD603": "DESIGN PROJECT 3",
    "DD605": "INTERNSHIP",
    "DD607": "DESIGN RESEARCH SEMINAR",
    "DD613": "Design for Society and Service Design",
    "DD623": "STRATEGIC DESIGN MANAGEMENT",
    "DD633": "Major Campaign Planning & Design",
    "DD635": "Advance Animation and Game Design",
    "DD651": "ORGANIZATIONAL MODEL FOR ENTREPRENEURSHIP",
    "DD653": "SERVICE AND MOBILITY DESIGN",
    "DD655": "ELECTIVE FROM OTHER DISIPLINE",
    "DD901": "Design for All",
    "DSC501": "MATHEMATICAL FOUNDATIONS OF COMPUTER SCIENCE",
    "DSC503": "DATA MANAGEMENT AND ETHICS",
    "DSC5201": "SEMINAR",
    "DSC5301": "PROJECT WORK",
    "DSC5405": "Advanced Operating System",
    "DSC601": "MAJOR PROJECT I",
    "DSC6205": "Statistical Tool",
    "DSC6309": "Swarm and Evolutionary Computing",
    "DSC6405": "Internet of Things",
    "EC101": "BASIC ELECTRONICS & COMMUNICATION ENGINEERING",
    "EC103": "ELECTRONIC WORKSHOP I",
    "EC201": "ANALOG ELECTRONICS – I",
    "EC203": "DIGITAL DESIGN - I",
    "EC205": "SIGNALS & SYSTEMS",
    "EC207": "ENGINEERING ANALYSIS & DESIGN (NETWORK ANALYSIS AND SYNTHESIS)",
    "EC251": "BASIC ELECTRONICS & INSTRUMENTATION",
    "EC261": "ANALOG  ELECTRONICS",
    "EC271a": "DIGITAL ELECTRONICS",
    "EC301": "DIGITAL COMMUNICATION",
    "EC303": "LINEAR INTEGRATED CIRCUITS",
    "EC305": "Semiconductor Device Electronics",
    "EC307": "ANTENNA DESIGN",
    "EC309": "Bio-Medical Electronics & Instrumentation",
    "EC311": "ALGORITHMS ANALYSIS AND DESIGN",
    "EC313": "MICROPROCESSORS AND INTERFACING",
    "EC315": "COMPUTER COMMUNICATION NETWORKS",
    "EC323": "CONTROL SYSTEMS",
    "EC325": "Probability and Random Process",
    "EC391": "MINI PROJECT",
    "EC393": "RESEARCH WORK",
    "EC395": "Entrepreneurship and Venture Development",
    "EC401": "B.TECH PROJECT-I",
    "EC403": "TRAINING SEMINAR",
    "EC407": "OPTICAL COMMUNICATION",
    "EC409": "COMPUTER VISION",
    "EC455": "Data Analytics",
    "EE101": "BASIC ELECTRICAL ENGINEERING",
    "EE101": "BASIC ELECTRICAL ENGINEERING -I",
    "EE103": "ELECTRICAL WORKSHOP",
    "EE105": "BASIC ELECTRICAL ENGINEERING -II",
    "EE201": "NETWORK ANALYSIS & SYNTHESIS",
    "EE203": "ELECTRONIC DEVICES AND CIRCUITS",
    "EE205": "ELECTROMECHANICAL ENERGY CONVERSION AND TRANSFORMER",
    "EE207a": "Electromagnetic Field Theory",
    "EE251": "ELECTRONIC INSTRUMENTATION AND MEASUREMENTS",
    "EE301": "POWER ELECTRONICS",
    "EE303": "POWER TRANSMISSION AND DISTRIBUTION",
    "EE305": "SIGNALS AND SYSTEMS",
    "EE307": "POWER STATION PRACTICES",
    "EE309": "SPECIAL ELECTRICAL MACHINES",
    "EE313a": "Engineering Analysis and Design",
    "EE317": "RENEWABLE ENERGY SYSTEMS",
    "EE319": "DIGITAL SYSTEM DESIGN",
    "EE321": "SOFT COMPUTING TECHNIQUES",
    "EE323": "FUNDAMENTALS OF MACHINE LEARNING",
    "EE325": "INTERNET OF THINGS",
    "EE357": "UTILIZATION OF ELECTRICAL ENERGY",
    "EE393": "RESEARCH WORK",
    "EE395": "Entrepreneurship and Venture Development",
    "EE401": "B.TECH PROJECT-I",
    "EE403": "TRAINING SEMINAR",
    "EE407": "INSTRUMENTATION AND MEASUREMENT",
    "EE409": "SWITCHGEAR AND PROTECTION",
    "EFM-07": "FUTURE, OPTIONS AND RISK MANAGEMENT",
    "EFM-08": "PROJECT APPRAISAL AND FINANCE",
    "EHR-01": "MANAGEMENT OF INDUSTRIAL RELATIONS AND LABOUR LEGISLATION",
    "EHR-04": "Human Resource Development - Strategies and Systems",
    "EIT-07": "E-GOVERNANCE",
    "EIT-11": "Data Analytics I",
    "EKTM-01": "INTERNET BUSINESS MODELS AND BUSINESS STRATEGIES",
    "EKTM-08": "E-BUSINESS AND E-COMMERCE",
    "EMBA-301": "STRATEGIC MANAGEMENT",
    "EMBA-302": "INTERNATIONAL BUSINESS ENVIRONMENT",
    "EMBA-303": "INFORMATION TECHNOLOGY MANAGEMENT",
    "EMBA-308": "MINOR PROJECT",
    "EMBA-309": "COMPREHENSIVE VIVA VOCE",
    "EMK-01": "INTERNATIONAL MARKETING MANAGEMENT",
    "EMK-04": "ADVERTISING AND BRAND MANAGEMENT",
    "EMK-08": "CUSTOMER RELATIONSHIP MANAGEMENT",
    "EN103": "WATER AND WASTEWATER ANALYSIS",
    "EN201": "STRENGTH OF MATERIALS",
    "EN203": "ENGINEERING & ENVIRONMENTAL SURVEYING",
    "EN205": "ENVIRONMENTAL CHEMISTRY & MICROBIOLOGY",
    "EN207": "ENGINEERING ANALYSIS & DESIGN",
    "EN301": "WASTE WATER ENGINEERING: DESIGN AND APPLICATIONS",
    "EN303": "INSTRUMENTATION TECHNIQUES FOR ENVIRONMENTAL MONITORING",
    "EN305": "SOIL POLLUTION AND REMEDIATION",
    "EN307": "PLANNING AND DESIGN OF ENVIRONMENTAL ENGINEERING WORKS",
    "EN309": "Water Resources System",
    "EN311": "CLIMATE CHANGE & CDM",
    "EN317": "Environmental Management",
    "EN395": "Entrepreneurship and Venture Development",
    "EN401": "B.TECH PROJECT-I",
    "EN403": "TRAINING SEMINAR",
    "EN409": "INDUSTRIAL WASTE MANAGEMENT",
    "EN411": "OCCUPATIONAL HAZARDS, HEALTH & SAFETY",
    "EN421": "Design of Water Distribution Network",
    "ENE5201": "SEMINAR",
    "ENE5301": "ENVIRONMENTAL CHEMISTRY & MICROBIOLOGY",
    "ENE5401": "INDUSTRIAL WASTEWATER TREATMENT",
    "ENE601": "MAJOR PROJECT I",
    "ENE6201": "HAZARDOUS WASTE MANAGEMENT",
    "ENE6301": "AIR QUALITY MODELING",
    "ENE6401": "ENVIRONMENT IMPACT ASSESSMENT & AUDIT",
    "EP103": "ENGINEERING PHYSICS WORKSHOP-I",
    "EP201": "INTRODUCTION TO COMPUTING",
    "EP203": "MATHEMATICAL PHYSICS",
    "EP205": "CLASSICAL AND QUANTUM MECHANICS",
    "EP207": "DIGITAL ELECTRONICS (ENGINEERING ANALYSIS AND DESIGN)",
    "EP301": "SEMICONDUCTOR DEVICES",
    "EP303": "ELECTROMAGNETIC THEORY, ANTENNAS AND PROPAGATION",
    "EP305": "ATOMIC AND MOLECULAR PHYSICS",
    "EP307": "BIOPHYSICS",
    "EP309": "QUANTUM INFORMATION AND COMPUTING",
    "EP317": "Advanced Semiconductor Device Physics",
    "EP321": "Advanced Wafer Processing",
    "EP393": "RESEARCH WORK",
    "EP401": "B.TECH PROJECT-I",
    "EP403": "TRAINING SEMINAR",
    "EP405": "VLSI AND FPGA DESIGN",
    "EP411": "ADVANCED SIMULATION TECHNIQUES IN PHYSICS",
    "EP415": "NANO SCIENCE AND TECHNOLOGY",
    "EP419": "INTRODUCTION TO AUTOMATION AND MOTION CONTROL",
    "EP423": "SPACE AND ATMOSPHERIC SCIENCE-I",
    "EP427a": "Advanced Materials for Photonic Devices",
    "ESCM-02": "INTERNATIONAL LOGISTICS MANAGEMENT",
    "ESCM-05": "SCM AND CUSTOMERS RELATIONSHIP MANAGEMENT",
    "FEC015": "Sociology  of Development",
    "FEC016": "Universal  human Values 1: Self and Family",
    "FEC1": "Sports I",
    "FEC10": "COMMUNICATION  SKILLS",
    "FEC10": "Communication Skills",
    "FEC11": "Soft Skills and Personality Development ",
    "FEC11": "Soft Skills and Personality Development",
    "FEC12": "BUSINESS  COMMUNICATION AND PRESENTATION SKILLS",
    "FEC12": "Business Communication and Presentation Skills",
    "FEC13": "Public Speaking",
    "FEC14": "APPRECIATION OF SHORT STORIES",
    "FEC15": "APPRECIATION OF POETRY & POSE",
    "FEC15": "Appreciation of Poetry & Prose",
    "FEC16": "APPRECIATION OF FICTION",
    "FEC18": "FINANCIAL  STATEMENTS ANALYSIS",
    "FEC18": "Financial Statements Analysis ",
    "FEC2": "SPORTS II",
    "FEC2": "Sports II ",
    "FEC22": "YOGA",
    "FEC24": "MUSIC",
    "FEC25": "Universal Human Values: I Self-Family",
    "FEC27": "PROFESSIONAL ETHICS & HUMAN VALUES",
    "FEC28": "Emotional Intelligence",
    "FEC3": "PHYSICAL EDUCATION AND SPORTS",
    "FEC32": "Logical Reasoning",
    "FEC37": "FRENCH",
    "FEC39": "JAPANESE",
    "FEC40": "GERMAN",
    "FEC45": "ENGINEERING  EXPLORATION",
    "FEC45": "Engineering Exploration",
    "FEC46": "TECHNICAL  COMMUNICATION",
    "FEC46": "Technical Communication",
    "FEC47": "Value Driven Leadership",
    "FEC48": "INTRODUCTION TO BIOLOGICAL SCIENCE",
    "FEC49": "SKETCHING & RENDERING",
    "FEC5": "NCC",
    "FEC50": "Tinkering Studio & Elements of Design",
    "FEC51": "Entrepreneurship Exploration ",
    "FEC51": "Entrepreneurship Exploration",
    "FEC52": "Extension and Outreach Activities",
    "FEC52": "Extension Outreach Activities",
    "FEC53": "Communicative Hindi (Only for foreign national students)",
    "FEC54": "Negotiation and Leadership",
    "FEC54": "Negotiation & Leadership",
    "FEC56": "Universal Human Values: Understanding Harmony",
    "FEC56": "UNIVERSAL HUMAN VALUES : UNDERSTANDING HARMONY",
    "FEC57": "Leadership Through Self-Management",
    "FEC58": "Science and Practice of Happiness",
    "FEC58": "SCIENCE & PRACTICE OF HAPPINESS",
    "FEC6": "Corporate Social Responsibility",
    "FEC7": "INTRODUCTION  TO ENVIRONMENTAL SCIENCE",
    "FEC7": "Introduction to Environmental Sciences",
    "FEC9": "Spoken Skills in English",
    "GE001a": "Econometrics",
    "GE005a": "Digital Marketing Analytics",
    "GEO501": "REMOTE SENSING, PHOTOGRAMMETRY AND SATELLITE IMAGE PROCESSING",
    "GTE501": "ADVANCED SOIL MECHANICS",
    "GTE503": "ADVANCE FOUNDATION ENGINEERING",
    "GTE5201": "SEMINAR",
    "GTE5303": "STABILITY ANALYSIS OF SLOPES",
    "GTE5401": "GEO-ENVIRONMENTAL ENGINEERING",
    "HU301a": "Engineering Economics",
    "HU305": "Macroeconomics",
    "HU307": "Basic Econometrics",
    "HU309": "Indian Economy",
    "HU313": "Creative Writing Skills",
    "HU315": "Non-Verbal Communication",
    "HU403": "Economic Growth",
    "HU409": "Soft Skills Development",
    "HU413": "Advanced Spoken Skills",
    "HU-703": "ECONOMETRICS",
    "HU-708": "Gender and Technology",
    "IBT501": "BIOENERGY",
    "IEM501": "Data Analytics",
    "IEM503": "Production & Operation Management",
    "IEM5205": "Principles of Managment",
    "IEM5305": "Total Quality Management",
    "IEM5407": "Product Design & Development",
    "IEM601": "MAJOR PROJECT I",
    "ISY5409": "Image Analysis",
    "ISY601": "MAJOR PROJECT I",
    "ISY6201": "Open Area Research Seminar",
    "ISY6321": "Malware Analysis",
    "ISY6413": "Mobile Computing",
    "IT103": "FUNDAMENTALS OF WEB DESIGN",
    "IT201": "DATA STRUCTURES",
    "IT203": "OBJECT ORIENTED PROGRAMMING",
    "IT205": "DISCRETE  STRUCTURES",
    "IT207": "ENGINEERING ANALYSIS AND DESIGN(MODELING & SIMULATION)",
    "IT301": "THEORY OF COMPUTATION",
    "IT303": "COMPUTER NETWORKS",
    "IT307": "PATTERN RECOGNITION",
    "IT315": "Distributed Systems",
    "IT317": "SOFT COMPUTING",
    "IT319": "Data Compression",
    "IT321": "MALWARE ANALYSIS",
    "IT323": "MACHINE LEARNING",
    "IT359": "JAVA PROGRAMMING",
    "IT391": "MINI PROJECT",
    "IT395": "Entrepreneurship and Venture Development",
    "IT401": "B.TECH PROJECT-I",
    "IT403": "TRAINING SEMINAR",
    "IT405": "DATA-WAREHOUSE AND DATA MINING",
    "IT407": "INFORMATION AND NETWORK SECURITY",
    "IT411": "DIGITAL IMAGE PROCESSING",
    "IT425": "NATURAL LANGUAGE PROCESSING",
    "IT429": "CYBER LAWS",
    "IT431": "INFORMATION SECURITY AND AUDIT",
    "IT433": "MULTI MODAL DATA PROCESSING",
    "ITY501": "LINEAR ALGEBRA AND PROBABILITY",
    "ITY503": "DATA STRUCTURE AND ALGORITHM",
    "ITY5201": "Seminar",
    "ITY5301": "Artificial Intelligence",
    "ITY5409": "Image Analysis",
    "MA101": "MATHEMATICS - I",
    "MA261": "NUMERICAL AND ENGINEERING OPTIMIZATION METHODS",
    "MC261": "NUMERICAL AND ENGINEERING OPTIMIZATION METHODS",
    "MAE201": "INDIAN ECONOMY",
    "MAE203": "DEVELOPMENT ECONOMICS",
    "MAE205": "DISSERTATION",
    "MAE207": "WORKSHOP",
    "MAE209": "Game Theory 1",
    "MAE223": "Time Series Analysis",
    "MAE233": "Corporate Finance",
    "MB101": "MANAGEMENT PROCESS & ORGANIZATIONAL BEHAVIOUR",
    "MB102": "MARKETING MANAGEMENT ",
    "MB103": "BUSINESS RESEARCH METHODS ",
    "MB104": "FINANCIAL ACCOUNTING & COST ANALYSIS",
    "MB105": "MANAGERIAL ECONOMICS ",
    "MB106": "BUSINESS COMMUNICATION ",
    "MB107": "INTRODUCTION TO BUSINESS ANALYTICS",
    "MB108": "DATABASE MANAGEMENT SYSTEMS ",
    "MB109": "DATA QUERYING & VISUALIZATION ",
    "MB205a": "Introduction to Programming using Python",
    "MB207": "PREDICTIVE MODELlING",
    "MB207": "Predictive Modeling",
    "MB301": "SUMMER INTERNSHIP",
    "MB302": "MACHINE LEARNING",
    "MB303": "BIG DATA ANALYTICS",
    "MB304a": "R FOR MACHINE LEARNING",
    "MB305": "BIG DATA ANALYTICS LAB",
    "MBA-101": "MANAGEMENT PROCESS AND ORGANIZATIONAL BEHAVIOR",
    "MBA-103": "MANAGERIAL ECONOMICS",
    "MBA-105": "FINANCIAL & COST ACCOUNTING",
    "MBA-107": "MARKETING MANAGEMENT",
    "MBA-109": "LEGAL ASPECTS OF BUSINESS",
    "MBA-111": "DECISION SCIENCES",
    "MBA-113": "BUSINESS COMMUNICATIONS AND INTERVIEW SKILLS",
    "MBA-115": "DATA MANAGEMENT LAB (SKILL BASED)",
    "MBA-201": "STRATEGIC MANAGEMENT",
    "MBA-203": "Corporate Governance and Social Responsibility",
    "MBA-205": "Applied Business Analytics and Intelligence",
    "MBA-207": "Critical Thinking and Problem Solving",
    "MBA-209": "Summer Internship Program",
    "MBAAN211": "Business Intelligence and Analytics",
    "MBAAN213": "Data Analytics in Finance",
    "MBAFM211": "Investment Management",
    "MBAFM213": "Investment Banking and Financial Services",
    "MBAFM-213": "Investment Banking and Financial Services",
    "MBAFM221": "Project Appraisal and Finance",
    "MBAHR211": "Industrial Relations & Labor Legislation",
    "MBAHR213": "Compensation Management",
    "MBAHR217": "Strategic Human Resource Management",
    "MBAMK211": "Digital Marketing Strategy",
    "MBAMK213": "Consumer Behaviour",
    "MBAMK215": "Product and Brand Management",
    "MBAMK219": "Marketing Research",
    "MBASC211": "Operational Analytics",
    "MBASC221": "Supply Chain Planning and Execution",
    "MBD002": "Marketing Analytics",
    "MBD004": "Financial Analytics",
    "MBEALS2": "ACTION LEARNING SEGMENT 2",
    "MBG009": "Security Analysis and Portfolio Management",
    "MBG014": "Logistics Planning and Strategy",
    "MBG016": "INTERNATIONAL MARKETING",
    "MC103": "PYTHON PROGRAMMING",
    "MC201": "DISCRETE MATHEMATICS",
    "MC203": "MATHEMATICS-III",
    "MC205": "PROBABILITY & STATISTICS",
    "MC207": "ENGINEERING ANALYSIS AND DESIGN (DIFFERENTIAL EQUATIONS AND APPLICATIONS)",
    "MC251": "APPLIED MATHEMATICS",
    "MC301": "OPERATING SYSTEM",
    "MC303": "STOCHASTIC PROCESSES",
    "MC305": "OPERATIONS RESEARCH",
    "MC307": "OBJECT ORIENTED PROGRAMMING",
    "MC315": "MODERN ALGEBRA",
    "MC391": "MINI PROJECT",
    "MC393": "RESEARCH WORK",
    "MC401": "B.TECH PROJECT-I",
    "MC403": "TRAINING SEMINAR",
    "MC405": "GRAPH THEORY",
    "MC407": "CRYPTOGRAPHY & NETWORK SECURITY",
    "MC409": "MATHEMATICAL MODELING & SIMULATION",
    "MC419": "Machine Learning",
    "ME101": "BASIC MECHANICAL ENGINEERING",
    "ME101": "COMPUTER AIDED ENGINEERING GRAPHICS-I",
    "ME103": "WORKSHOP PRACTICE",
    "ME105": "ENGINEERING GRAPHICS",
    "ME105": "COMPUTER AIDED ENGINEERING GRAPHICS-II",
    "ME107": "BASIC MECHANICAL ENGINEERING",
    "ME201": "MECHANICS OF SOLIDS",
    "ME203": "THERMAL ENGINEERING - I",
    "ME205": "MACHINE DRAWING AND SOLID MODELING",
    "ME207": "ENGINEERING ANALYSIS AND DESIGN",
    "ME251": "ENGINEERING MECHANICS",
    "ME261": "KINEMATIC AND DYNAMIC OF MACHINES",
    "ME301": "FLUID SYSTEMS",
    "ME303": "DYNAMICS OF MACHINES",
    "ME351a": "POWER PLANT ENGINEERING",
    "ME353": "RENEWABLE SOURCES OF ENERGY",
    "ME361": "INDUSTRIAL ENGINEERING",
    "ME365": "COMPUTATIONAL FLUID DYNAMICS",
    "ME367": "FINITE ELEMENT METHODS",
    "ME371": "VALUE ENGINEERING",
    "ME391": "Mini Project",
    "ME395": "Entrepreneurship and Venture Development",
    "ME401": "B.TECH PROJECT-I",
    "ME403": "TRAINING SEMINAR",
    "ME407": "REFRIGERATION & AIR CONDITIONING",
    "ME409": "MECHATRONICS & CONTROL",
    "ME411": "I.C. ENGINES",
    "ME413": "METROLOGY",
    "ME419": "ROBOTICS & AUTOMATION",
    "ME423": "ADVANCED MANUFACTURING PROCESSES",
    "ME427": "OPERATIONS RESEARCH",
    "ME429": "INDUSTRIAL TRIBOLOGY",
    "ME431": "NON-CONVENTIONAL ENERGY SOURCES",
    "ME435": "OPTIMIZATION TECHNIQUES",
    "MG301": "Fundamentals of Management",
    "MGF-01": "Investment Management",
    "MGF-07a": "Financial Derivatives",
    "MGF-11": "Financial Statement and Analysis",
    "MGH-01": "Industrial Relations & Labour Legislation",
    "MGH-08": "Training and Development",
    "MGI-02": "Business Systems Analysis And Design",
    "MGI-03": "Database Management System",
    "MGM-01": "CONSUMER BEHAVIOR",
    "MGM-06": "MARKETING RESEARCH",
    "MGS-01": "SCM and E-Commerce",
    "MGS-03": "Logistics Planning and Strategy",
    "MGT-11": "MANAGEMENT PROCESS AND ORGANIZATIONAL BEHAVIOR",
    "MGT-12": "FINANCIAL ACCOUNTING AND COST ACCOUNTING",
    "MGT-13": "MARKETING MANAGEMENT",
    "MGT-14": "MANAGERIAL ECONOMICS",
    "MGT-15": "DECISION SCIENCES",
    "MGT-16": "LEGAL ASPECTS OF MANAGEMENT",
    "MGT-17": "BUSINESS COMMUNICATION",
    "MGT-18": "DATA ANALYSIS TECHNIQUES",
    "MGT-31": "Business Analytics",
    "MGT-32": "Corporate Governance",
    "MGT-33": "Strategic Management",
    "MGT-34": "Summer internship Report",
    "MGT-35": "Managerial Skills Development (NUES)",
    "MOOC301": "MOOC COURSE 301",
    "MOOC303": "MOOC COURSE 303",
    "MOOC401": "MOOC401",
    "MOOC403": "MOOC403",
    "MOOC6201": "MOOC",
    "MOOC6301": "MOOC",
    "MOOC6401": "MOOC",
    "MOOC6403": "MOOC",
    "MOOC901": "Mooc against Research Methodology",
    "MOOC903": "Mooc against Research and Publication Ethics",
    "MOOC905": "Mooc Against 4 Credit Course",
    "MOOC907": "Mooc Against 3 Credit Course",
    "MOOC909": "Mooc Against 2 Credit Course",
    "MSBT201": "Bioprocess Engineering & Technology",
    "MSBT203": "Immunotechnology and Molecular Virology",
    "MSBT205": "IPR & Biosafety",
    "MSBT217": "Nanobiotechnology",
    "MSBT241": "Molecular Therapeutics",
    "MSBT243": "Lab based on Elective",
    "MSCH201": "Organic Chemistry-3",
    "MSCH203": "Physical Chemistry-3",
    "MSCH205": "Inorganic Chemistry - 3",
    "MSCH207b": "INORGANIC REACTION MECHANISMS AND BIOINORGANIC CHEMISTRY",
    "MSCH207c": "ORGANIC SYNTHESIS AND HETEROCYCLIC CHEMISTRY              ",
    "MSCH207d": "SOLID STATE CHEMISTRY",
    "MSCH209a": "SPECIALIZATION LABORATORY (INORGANIC CHEMISTRY)",
    "MSCH209b": "SPECIALIZATION LABORATORY (ORGANIC CHEMISTRY)",
    "MSCH209c": "SPECIALIZATION LABORATORY (PHYSICAL CHEMISTRY)",
    "MSMA105": "ORDINARY DIFFERENTIAL EQUATIONS",
    "MSMA107": "DISCRETE MATHEMATICS",
    "MSMA109": "MATHEMATICAL STATISTICS",
    "MSMA201": "Functional Analysis",
    "MSMA203": "Operation Research",
    "MSMA205": "Dissertation-I",
    "MSMA211": "Number Theory",
    "MSMA213": "Mathematical Modeling And Simulation",
    "MSMA219": "Database Management System",
    "MSPH201": "ATOMIC AND MOLECULAR PHYSICS",
    "MSPH203": "NUCLEAR AND PARTICLE PHYSICS",
    "MSPH205": "DISSERTATION-1",
    "MSPH207": "Fibre and Integrated  Optics",
    "MSPH211": "ADVANCED PHYSICS LAB-I",
    "MSPH215": "Plasma Physics",
    "MSPH217": "Characterization Techniques",
    "NST502": "ANALYTICAL TECHNIQUES",
    "NST504": "DESIGN AND SYNTHESIS OF NANOSTRUCTURES",
    "OED361": "Clay, Ceramics and Glass Moulding",
    "OED363": "Metal, Plastic and Mix Material Study",
    "PE103": "WORKSHOP PRACTICE",
    "PE201": "ENGINEERING MATERIALS & METALLURGY",
    "PE203": "THERMAL ENGINEERING-I",
    "PE205": "MANUFACTURING MACHINES",
    "PE207": "ENGINEERING ANALYSIS AND DESIGN(MODELING  AND SIMULATION)",
    "PE251": "ENGINEERING MATERIALS AND METALLURGY",
    "PE261": "QUANTITATIVE TECHNIQUES",
    "PE301": "CASTING TECHNOLOGY",
    "PE303": "PRODUCTION PLANNING & CONTROL",
    "PE305": "ADVANCE MACHINE DESIGN",
    "PE315": "MECHATRONICS",
    "PE351": "Advance Machining Process",
    "PE353": "SUPPLY CHAIN MANAGEMENT",
    "PE353a": "SUPPLY CHAIN MANAGEMENT",
    "PE357": "PRODUCT DESIGN & SIMULATION",
    "PE361": "TOTAL QUALITY MANAGEMENT",
    "PE361a": "TOTAL QUALITY MANAGEMENT",
    "PE395": "Entrepreneurship and Venture Development",
    "PE401": "B.TECH PROJECT-I",
    "PE403": "TRAINING SEMINAR",
    "PE411": "COMPUTER INTEGRATED DESIGN AND MANUFACTURING",
    "PE417": "MATERIALS MANAGEMENT",
    "PE419": "PROJECT MANAGEMENT",
    "PE423": "THERMAL SPRAY TECHNOLOGY",
    "PES501": "Modeling of Electrical Systems",
    "PES503": "Power Electronics Convertors",
    "PES5201": "SEMINAR",
    "PES5203": "RENEWABLE ENERGY SYSTEMS",
    "PES5307": "POWER ELECTRONICS FOR PHOTOVOLTAIC AND WIND ENERGY SYSTEMS",
    "PES5405": "SWITCH MODE POWER CONVERTERS",
    "PES6209": "Artificial Intelligence",
    "PRD5201": "SEMINAR",
    "PSY5205": "FORECASTING TECHNIQUES IN POWER SYSTEMS",
    "PTE501": "Polymer Chemistry",
    "PTE5307": "Green Polymers",
    "SE103": "COMPUTER WORKSHOP - I",
    "SE201": "DATA STRUCTURES",
    "SE203": "OBJECT ORIENTED PROGRAMMING",
    "SE205a": "Operating System",
    "SE207a": "Engineering Analysis and Design ( Software Engineering)",
    "SE301": "OBJECT ORIENTED SOFTWARE ENGINEERING",
    "SE301a": "Software Testing",
    "SE303a": "Software Quality Metrics",
    "SE305": "Software Requirement Engineering",
    "SE313": "Advanced Data Structures",
    "SE323": "THEORY OF COMPUTATION",
    "SE325": "WEB TECHNOLOGY",
    "SE327": "METHODS FOR DATA ANALYSIS",
    "SE333": "Minor Project",
    "SE391": "MINI PROJECT",
    "SE393": "RESEARCH WORK",
    "SE395": "Entrepreneurship and Venture Development",
    "SE401": "B.TECH PROJECT-I",
    "SE403": "TRAINING SEMINAR",
    "SE405": "SOFTWARE PROJECT MANAGEMENT",
    "SE407a": "Data Warehousing and Data Mining",
    "SE409": "SOFTWARE MAINTENANCE",
    "SE425": "Intellectual Property Rights & Cyber laws",
    "SE427": "Software Project Management",
    "SE429": "Data Warehouse & Data Mining",
    "SM-901": "RESEARCH METHODOLOGY",
    "SM-903": "RESEARCH AND PUBLICATION ETHICS",
    "SPD501": "ADVANCED DIGITAL SIGNAL PROCESSING",
    "SPD503": "IMAGE ANALYSIS AND PROCESSING",
    "SPD5201": "SEMINAR",
    "SPD5303": "Wavelets in Signal Processing",
    "SPD6301": "Data Analytics",
    "SPD6407": "Digital Design and verification",
    "STE501": "STRUCTURAL DYNAMICS",
    "STE503": "COMPUTATIONAL METHODS IN STRUCTURAL ENGINEERING",
    "STE5201": "SEMINAR",
    "STE5303": "THEORY OF ELASTICITY & PLASTICITY",
    "STE5401": "DESIGN OF ADVANCED REINFORCED CONCRETE STRUCTURES",
    "STE5405": "PRESTRESSED CONCRETE DESIGN",
    "STE601": "MAJOR PROJECT I",
    "STE6201": "Sustainable Building Technologies",
    "STE6301": "Instrumentation & Rehabilitation of Structures",
    "STE6407": "Retrofitting Structures",
    "SWE501": "SOFTWARE REQUIREMENT ENGINEERING",
    "SWE503": "OBJECT ORIENTED SOFTWARE ENGINEERING",
    "SWE5201": "SEMINAR",
    "SWE5301": "PROJECT WORK",
    "SWE5405": "Advanced Operating System",
    "SWE601": "MAJOR PROJECT I",
    "SWE6205": "Statistical Tools",
    "SWE6309": "Swarm and Evolutionary Computing",
    "SWE6405": "THINGS OF THE INTERNET",
    "SWE651": "RESEARCH PROJECT",
    "VAC11": "Leadership Through Self-Management",
    "VAC12": "NCC",
    "VAC13": "Negotiation & Leadership",
    "VAC16": "Professional Ethics & Human Values",
    "VAC19": "Science & Practice Of Happiness",
    "VAC20": "Sports I",
    "VAC21": "Sports II ",
    "VAC22": "Universal Human Values: I Self-Family",
    "VAC24": "Universal Human Values: Understanding Harmony",
    "VAC25": "Value Driven Leadership",
    "VAC27": "Introduction to Environmental Science",
    "VAC3": "Corporate Social Responsibility",
    "VAC5": "Emotional Intelligence",
    "VAC6": "Extension Outreach Activities",
    "VAC9": "Introduction to Biological Science",
    "VLS501": "ANALOG IC DESIGN",
    "VLS503": "DIGITAL CMOS IC DESIGN",
    "VLS5201": "Seminar",
    "VLS5307": "Organic and Flexible Electronics",
    "VLS601": "MAJOR PROJECT I",
    "VLS6207": "Selected topics in VLSI",
    "VLS6305": "Machine Learning",
    "VLS6401": "Mixed Signal  Design",

}
